# Generated by Django 4.2 on 2023-04-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='copies',
            field=models.IntegerField(),
        ),
    ]
    
