# Generated by Django 4.2 on 2023-04-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_bookdetails_copies'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('copies', models.IntegerField(max_length=10)),
            ],
        ),
    ]
