# Generated by Django 5.1.4 on 2025-01-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='copies',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='copies',
            field=models.IntegerField(),
        ),
    ]
