# Generated by Django 5.1.4 on 2025-01-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_bookdetails_copies_alter_borrow_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='book_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
