# Generated by Django 5.1.4 on 2025-03-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_add_shelf_level_column_to_bookdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetails',
            name='address',
        ),
    ]
